layout_spectrum: 0.6168387397228381
typography_spectrum: 0.5763979694951731
color:
  brandColors:
    - '#FF7F00'
    - '#3C3C3C'
    - '#FFFFFF'
    - '#040404'
    - '#A6A39C'
  brandStrength: 0.03208300578241965
  lightness: 0.028470483347865762
  saturation: 0.9315326187563231
  rhythmicContrast: 0.02645206152867194
name: CAN-BIKE BC
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/401748e7-3ff7-413c-8fd2-c4f0e2d4bb09.png
analytics:
  twitter: 'https://twitter.com/chuckglover1'
opengraph:
  type: ''
  appId: ''
title: CAN-BIKE British Columbia
description: Welcome to Canbikebc.ca
author:
  name: Design by Ken McGonigal
  url: 'https://aegisnetworks.ca'
  email: ken.mcgonigal@aegisnetworks.ca
content_rating:
  adult: false
navigation:
  - name: Courses
    url: 'https://courses.canbikebc.ca'
    type: external
  - name: Blog
    url: 'https://courses.canbikebc.ca/canbikebcblog'
    type: external
  - name: About
    id: 6c670daa-c868-4c58-84ce-e07ffe6f519f
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fbf7dc8-b066-49d8-9ea5-357920da0595.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fbf7dc8-b066-49d8-9ea5-357920da0595.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/79567dd5-c715-4dcb-8023-7a1dc613749c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/79567dd5-c715-4dcb-8023-7a1dc613749c.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
