typography_spectrum: 0.7946907515924351
color:
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#7C0000'
    - '#E9B67F'
    - '#F65D00'
  brandStrength: 1
  lightness: 0.2931907368372978
  saturation: 0.25521646937041886
  rhythmicContrast: 0.2730809293436532
github: true
layout_spectrum: 0.7409975927665202
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/709a6566-d911-48a1-94cf-064603872aeb.gif
name: canbikebc
navigation:
  - name: Courses
    url: 'http://courses.canbikebc.ca'
    type: external
  - name: Canbike
    id: dca7f9c4-03db-4cbd-aaed-a204dfd923df
    type: content
  - name: About Me
    id: 6c670daa-c868-4c58-84ce-e07ffe6f519f
    type: content
title: Canbike British Columbia
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fbf7dc8-b066-49d8-9ea5-357920da0595.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fbf7dc8-b066-49d8-9ea5-357920da0595.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Welcome to Canbikebc.ca
