layout_spectrum: 0.46000984542818724
typography_spectrum: 1
color:
  brandColors:
    - '#FEA500'
    - '#3C3C3C'
    - '#FFFFFF'
    - '#A06700'
    - '#A6ABAF'
  brandStrength: 0.6873734717120851
  lightness: 0.4985475607821257
  saturation: 0.3644289620819105
  rhythmicContrast: 0.12212530446201932
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/709a6566-d911-48a1-94cf-064603872aeb.gif
name: canbikebc
navigation:
  - name: Courses
    url: 'https://courses.canbikebc.ca'
    type: external
  - name: Canbike
    id: dca7f9c4-03db-4cbd-aaed-a204dfd923df
    type: content
  - name: About Me
    id: 6c670daa-c868-4c58-84ce-e07ffe6f519f
    type: content
title: Canbike British Columbia
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fbf7dc8-b066-49d8-9ea5-357920da0595.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fbf7dc8-b066-49d8-9ea5-357920da0595.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/79567dd5-c715-4dcb-8023-7a1dc613749c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/79567dd5-c715-4dcb-8023-7a1dc613749c.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Welcome to Canbikebc.ca
author:
  name: Ken McGonigal
  url: 'https://aegisnetworks.ca'
  email: ken.mcgonigal@aegisnetworks.ca
