name: CAN-BIKE BC
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/333246a3-f7ed-4b0e-9a26-4e4b9c53eebd.png
layout_spectrum: 0.46000984542818724
typography_spectrum: 1
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#FEA500'
    - '#3C3C3C'
    - '#FFFFFF'
    - '#A06700'
    - '#A6ABAF'
  brandStrength: 0.6873734717120851
  lightness: 0.4985475607821257
  saturation: 0.3644289620819105
  rhythmicContrast: 0.12212530446201932
title: Canbike British Columbia
description: Welcome to Canbikebc.ca
author:
  name: Design by Ken McGonigal
  url: 'https://aegisnetworks.ca'
  email: ken.mcgonigal@aegisnetworks.ca
content_rating:
  adult: false
navigation:
  - name: Courses
    url: 'https://courses.canbikebc.ca'
    type: external
  - name: Blog
    url: 'https://courses.canbikebc.ca/canbikebcblog'
    type: external
  - name: About Me
    id: 6c670daa-c868-4c58-84ce-e07ffe6f519f
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fbf7dc8-b066-49d8-9ea5-357920da0595.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fbf7dc8-b066-49d8-9ea5-357920da0595.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/79567dd5-c715-4dcb-8023-7a1dc613749c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/79567dd5-c715-4dcb-8023-7a1dc613749c.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
analytics:
  twitter: 'https://twitter.com/chuckglover1'
