layout_spectrum: 0.13200928651985924
typography_spectrum: 0.7900112014407716
color:
  brandColors:
    - '#FFFFFF'
    - '#060604'
    - '#826662'
    - '#CF182C'
    - '#CFB761'
  brandStrength: 0.5813980847958585
  lightness: 0.07663087420663474
  saturation: 0.8603968254792145
  rhythmicContrast: 0.6904364098929384
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/709a6566-d911-48a1-94cf-064603872aeb.gif
name: canbikebc
navigation:
  - name: About
    id: 97db7c96-9b73-47ee-9159-9538235728a3
    type: content
title: Chuck's Cycling Corner
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fbf7dc8-b066-49d8-9ea5-357920da0595.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fbf7dc8-b066-49d8-9ea5-357920da0595.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Welcome to Canbikebc.ca
github: true
